on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Pages Build
    runs-on: ubuntu-latest
    steps:
    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.1.0
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 9.14.2
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Install Dependencies
      run: pnpm install
    - name: Build
      run: pnpm build
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/

  deploy:
    name: Deploy Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
    
