on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Pages Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.1.0
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 9.14.2
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Build
      run: pwd && ls && pnpm build
